### PR TITLE
Introducing ColorStyle to avoid dealing LCDColor

### PR DESCRIPTION
**Pull request by heltena**
I'm proposing the enum ColorStyle to use LCDSolidColor or LCDPattern in the Graphics methods. For example:

    let bitmap = Graphics.newBitmap(width: 100, height: 100, colorStyle: .solid(.colorBlack))
    let newSprite = Sprite(bitmap: bitmap)

Also, using patterns:

    let squares: LCDPattern = (
        0xF0, 0xF0, 0xF0, 0xF0, 0x0F, 0x0F, 0x0F, 0x0F,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
    )
    let bitmap = Graphics.newBitmap(width: 100, height: 100, colorStyle: .pattern(squares))
    let newSprite = Sprite(bitmap: bitmap)

It also works on Graphics methods, like:

    mySprite.withImage {
        Graphics.fillRect(x: x - 25, y: y - 25, width: 50, height: 50, colorStyle: .solid(.colorClear))
        Graphics.fillEllipse(
             x: x - 25, y: y - 25, 
             width: 50, height: 50, 
             startAngle: startAngle, endAngle: endAngle, 
             colorStyle: .solid(.colorBlack))
    }

### CODE REVIEW

**Comment by rauhul** [comment]
First, thank you for trying out these examples and getting involved. These changes are definitely something I'd like to see in a full featured Playdate Swift overlay.

That said _this_ repo isn't intended to be a full overlay, its purpose is to show what's possible. I think some other Playdate developers have forked this repo and are expanding on the overlay. I suggest retargeting this PR to one of those forks.

**Comment by heltena** [comment]
Oh, cool! I was just soo excited about this repo! Sorry about it, and thank you so much! I will keeping an eye on it!

**Comment by rauhul** [comment]
Absolutely no need to be sorry, I very much appreciate your interest and enjoyed trying out your example locally too! :D

**Comment by willco007** [comment]
@heltena Here is an active fork the community is working on, please submit a PR there:  https://github.com/jackson-57/playdate-swift-overlay.

**Comment by heltena** [comment]
Thanks for the repo. I'm having a look on it :-)

**Pull request closed without merging**
